### ISSUE TITLE
Error Chalk has no method 'grey' after update

### ISSUE THREAD

**Issue by fernando-nery** [gulpjs/fancy-log#7]
After chalk was updated last night with version 1.1.3 (https://github.com/chalk/chalk/releases), npm is requiring this version, as the log shows:

```
├─┬ fancy-log@1.2.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── escape-string-regexp@1.0.5 
│ │ └─┬ strip-ansi@3.0.1 
│ │   └── ansi-regex@2.0.0 
```

Since then, I am getting an error when compiling:

```
/node_modules/fancy-log/index.js:9
return '['+chalk.grey(timestamp('HH:mm:ss'))+']';
                    ^

TypeError: Object #<Chalk> has no method 'grey'
at getTimestamp (node_modules/fancy-log/index.js:9:20)
at log (node_modules/fancy-log/index.js:13:14)
at module.exports (node_modules/gulp-util/lib/log.js:11:14)
at Object.module.exports.logError (node_modules/gulp-notify/lib/extra_api.js:20:3)
at logError (node_modules/gulp-notify/lib/notify.js:91:11)
at node_modules/gulp-notify/lib/notify.js:63:7
at module.exports (node_modules/gulp-notify/lib/report.js:37:12)
at DestroyableTransform._flush (node_modules/gulp-notify/lib/notify.js:62:5)
at DestroyableTransform.<anonymous> (node_modules/gulp-notify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
at DestroyableTransform.g (events.js:180:16)
Process exited with code 8 
```

**Comment by Qix-** [comment]
ref chalk/chalk#107. This is strange indeed. Let me look a bit into this.

**Comment by phated** [comment]
The linked chalk issue was closed, so I'm going to close this.
